export const iconsUrls = {
    html: { iconUrl: "../../assets/logos/html.png", class:"html"},
    css: {iconUrl: "../../assets/logos/css.png", class:"css"},
    scss: {iconUrl: "../../assets/logos/sass.png", class:"scss"},
    javascript: { iconUrl: "../../assets/logos/javascript.png", class:"js" },
    typescript: { iconUrl: "../../assets/logos/typescript-transp.png", class:"ts" },
    angular: { iconUrl: "../../assets/logos/angular.png", class:"ng" },
    react: { iconUrl: "../../assets/logos/react.png", class:"react" },
    wordpress: { iconUrl: "../../assets/logos/wordpress.png", class:"wordpress" },
    tailwind: { iconUrl: "../../assets/logos/tailwind.png", class:"tw" },
    bootstrap: { iconUrl: "../../assets/logos/bootstrap.png", class:"bs" },
    ngBootstrap: { iconUrl: "../../assets/logos/ng-bootstrap.png", class:"ng-bs" },
    ngMaterial: { iconUrl: "../../assets/logos/ng-material.png", class:"ng-material" },
    ngKolkov: { iconUrl: "../../assets/logos/ng-kolkov.png", class:"kolkov" },
    leaflet: { iconUrl: "../../assets/logos/leaflet.svg", class:"leaflet" },
    karma: {iconUrl: "../../assets/logos/karma.png", class:"karma" },
    jasmine: { iconUrl: "../../assets/logos/jasmine.png", class:"jasmine" },
    node: { iconUrl: "../../assets/logos/nodejs.png", class:"node"},
    nodeSvg: { iconUrl: "../../assets/logos/nodejs-horizontal.svg", class:"node-svg"},
    express: { iconUrl: "../../assets/logos/express-js-seeklogo.com.svg", class:"exp"},
    ec2: { iconUrl: "../../assets/logos/ec2.png", class: "ng-bs" },
    ec2Horizontal: { iconUrl: "../../assets/logos/EC2.jpg", class: "ng-bs" },
    aws: { iconUrl: "../../assets/logos/AWS.png", class: "aws" },
    awsWhite: { iconUrl: "../../assets/logos/aws-white.png", class: "hidden" },
    mysql: {iconUrl: "../../assets/logos/mysql.png", class: "mysql"},
    firebase: {iconUrl: "../../assets/logos/firebase.png", class:"firebase"}
}